### ISSUE TITLE
Reproducible complete example with form included

### ISSUE THREAD

**Issue by myaseen208** [jlgraves-ubc/forms#2]
I'm struggling to understand the workflow of the package. Would highly appreciate it if you a reproducible complete example with form included may be provided. Thanks

**Comment by jlgraves-ubc** [comment]
Hi!  The file `example.qmd` provides a description of how to configure the forms extension on a webpage, and if you render it to HTML, it should also provide a reproducible example of the forms in operation.  Is there part of it that isn't working properly or is unclear?

**Comment by myaseen208** [comment]
Got it. Thanks.
