### ISSUE TITLE
Manipulating form element attributes

### ISSUE THREAD

**Issue by joshuaosoro** [jlgraves-ubc/forms#5]
I need to understand how to change attributes of the form element, specifically i need to add attribute `method="POST"` to form element so that i achieve <form method="POST">...</form>

How do i achieve this? Please help.

**Comment by jlgraves-ubc** [comment]
I can't see your link here, so I'm not sure what you're trying to do here.

I can probably just add that option to the form, or you can - I don't think it exists, currently, but it should be pretty easy to add.
